sandbox_mode = "danger-full-access"
approval_policy = "never"

[features]
hooks = true

[projects]
"/home/lizixuan/projects(WSL)/badminton-miniapp" = { trust_level = "trusted" }
"D:\\projects(WIN)\\badminton-miniapp" = { trust_level = "trusted" }
